image: golang:1.12.16

services:
  - docker:dind

variables:
  GOPROXY: direct

cache:
  paths:
  - vendor/

before_script:
  - docker info
  - go get -u golang.org/x/lint/golint
  - go mod vendor

lint:
    script:
      - go fmt $(go list ./... | grep -v /vendor/)
      - go vet $(go list ./... | grep -v /vendor/)
      - go list ./... | grep -v /vendor/ | xargs -L1 golint --set_exit_status

test:
    script:
      - go test -race $(go list ./... | grep -v /vendor/) -v -coverprofile=coverage.out
      - go tool cover -func=coverage.out

# build:
#   image: docker:latest
#   variables:
#     DOCKER_DRIVER: overlay2
#   services:
#     - docker:dind
#   before_script:
#     - docker info
#   script:
#     - docker build -t docker.uncharted.software/worldmodeler/wm-go .
#     - docker push docker.uncharted.software/worldmodeler/wm-go:latest
#   after_script:
#     - docker rmi docker.uncharted.software/worldmodeler/wm-go:latest