// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: tiles.proto

package tiles

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type TileStats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count     uint64  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"` // will be deprecated
	Sum       float64 `protobuf:"fixed64,2,opt,name=sum,proto3" json:"sum,omitempty"`    // Will be deprecated
	Avg       float64 `protobuf:"fixed64,3,opt,name=avg,proto3" json:"avg,omitempty"`    // will be deprecated
	SSumTSum  float64 `protobuf:"fixed64,4,opt,name=s_sum_t_sum,json=sSumTSum,proto3" json:"s_sum_t_sum,omitempty"`
	SSumTMean float64 `protobuf:"fixed64,5,opt,name=s_sum_t_mean,json=sSumTMean,proto3" json:"s_sum_t_mean,omitempty"`
	Weight    float64 `protobuf:"fixed64,6,opt,name=weight,proto3" json:"weight,omitempty"`
}

func (x *TileStats) Reset() {
	*x = TileStats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tiles_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TileStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TileStats) ProtoMessage() {}

func (x *TileStats) ProtoReflect() protoreflect.Message {
	mi := &file_tiles_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TileStats.ProtoReflect.Descriptor instead.
func (*TileStats) Descriptor() ([]byte, []int) {
	return file_tiles_proto_rawDescGZIP(), []int{0}
}

func (x *TileStats) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *TileStats) GetSum() float64 {
	if x != nil {
		return x.Sum
	}
	return 0
}

func (x *TileStats) GetAvg() float64 {
	if x != nil {
		return x.Avg
	}
	return 0
}

func (x *TileStats) GetSSumTSum() float64 {
	if x != nil {
		return x.SSumTSum
	}
	return 0
}

func (x *TileStats) GetSSumTMean() float64 {
	if x != nil {
		return x.SSumTMean
	}
	return 0
}

func (x *TileStats) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type TileBins struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stats     map[uint32]*TileStats `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	TotalBins uint32                `protobuf:"varint,2,opt,name=totalBins,proto3" json:"totalBins,omitempty"`
}

func (x *TileBins) Reset() {
	*x = TileBins{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tiles_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TileBins) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TileBins) ProtoMessage() {}

func (x *TileBins) ProtoReflect() protoreflect.Message {
	mi := &file_tiles_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TileBins.ProtoReflect.Descriptor instead.
func (*TileBins) Descriptor() ([]byte, []int) {
	return file_tiles_proto_rawDescGZIP(), []int{1}
}

func (x *TileBins) GetStats() map[uint32]*TileStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *TileBins) GetTotalBins() uint32 {
	if x != nil {
		return x.TotalBins
	}
	return 0
}

type TileCoord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X uint32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y uint32 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Z uint32 `protobuf:"varint,3,opt,name=z,proto3" json:"z,omitempty"` // zoom
	T int64  `protobuf:"varint,4,opt,name=t,proto3" json:"t,omitempty"` // seconds since unix epoch
}

func (x *TileCoord) Reset() {
	*x = TileCoord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tiles_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TileCoord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TileCoord) ProtoMessage() {}

func (x *TileCoord) ProtoReflect() protoreflect.Message {
	mi := &file_tiles_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TileCoord.ProtoReflect.Descriptor instead.
func (*TileCoord) Descriptor() ([]byte, []int) {
	return file_tiles_proto_rawDescGZIP(), []int{2}
}

func (x *TileCoord) GetX() uint32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *TileCoord) GetY() uint32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *TileCoord) GetZ() uint32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *TileCoord) GetT() int64 {
	if x != nil {
		return x.T
	}
	return 0
}

type Tile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Coord *TileCoord `protobuf:"bytes,1,opt,name=coord,proto3" json:"coord,omitempty"`
	Bins  *TileBins  `protobuf:"bytes,2,opt,name=bins,proto3" json:"bins,omitempty"`
}

func (x *Tile) Reset() {
	*x = Tile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tiles_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tile) ProtoMessage() {}

func (x *Tile) ProtoReflect() protoreflect.Message {
	mi := &file_tiles_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tile.ProtoReflect.Descriptor instead.
func (*Tile) Descriptor() ([]byte, []int) {
	return file_tiles_proto_rawDescGZIP(), []int{3}
}

func (x *Tile) GetCoord() *TileCoord {
	if x != nil {
		return x.Coord
	}
	return nil
}

func (x *Tile) GetBins() *TileBins {
	if x != nil {
		return x.Bins
	}
	return nil
}

var File_tiles_proto protoreflect.FileDescriptor

var file_tiles_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x74, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x74,
	0x69, 0x6c, 0x65, 0x73, 0x22, 0x9d, 0x01, 0x0a, 0x09, 0x54, 0x69, 0x6c, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x75, 0x6d, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x73, 0x75, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x76,
	0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x61, 0x76, 0x67, 0x12, 0x1d, 0x0a, 0x0b,
	0x73, 0x5f, 0x73, 0x75, 0x6d, 0x5f, 0x74, 0x5f, 0x73, 0x75, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x08, 0x73, 0x53, 0x75, 0x6d, 0x54, 0x53, 0x75, 0x6d, 0x12, 0x1f, 0x0a, 0x0c, 0x73,
	0x5f, 0x73, 0x75, 0x6d, 0x5f, 0x74, 0x5f, 0x6d, 0x65, 0x61, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x09, 0x73, 0x53, 0x75, 0x6d, 0x54, 0x4d, 0x65, 0x61, 0x6e, 0x12, 0x16, 0x0a, 0x06,
	0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x77, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x22, 0xa6, 0x01, 0x0a, 0x08, 0x54, 0x69, 0x6c, 0x65, 0x42, 0x69, 0x6e,
	0x73, 0x12, 0x30, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x74, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x54, 0x69, 0x6c, 0x65, 0x42, 0x69, 0x6e,
	0x73, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x73, 0x74,
	0x61, 0x74, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x42, 0x69, 0x6e, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x42, 0x69, 0x6e,
	0x73, 0x1a, 0x4a, 0x0a, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x26, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x74, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x54, 0x69, 0x6c, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x73, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x43, 0x0a,
	0x09, 0x54, 0x69, 0x6c, 0x65, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x01, 0x79, 0x12, 0x0c, 0x0a, 0x01, 0x7a, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x01, 0x7a, 0x12, 0x0c, 0x0a, 0x01, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x01, 0x74, 0x22, 0x53, 0x0a, 0x04, 0x54, 0x69, 0x6c, 0x65, 0x12, 0x26, 0x0a, 0x05, 0x63, 0x6f,
	0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x74, 0x69, 0x6c, 0x65,
	0x73, 0x2e, 0x54, 0x69, 0x6c, 0x65, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x52, 0x05, 0x63, 0x6f, 0x6f,
	0x72, 0x64, 0x12, 0x23, 0x0a, 0x04, 0x62, 0x69, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x74, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x54, 0x69, 0x6c, 0x65, 0x42, 0x69, 0x6e,
	0x73, 0x52, 0x04, 0x62, 0x69, 0x6e, 0x73, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x6c, 0x61,
	0x62, 0x2e, 0x75, 0x6e, 0x63, 0x68, 0x61, 0x72, 0x74, 0x65, 0x64, 0x2e, 0x73, 0x6f, 0x66, 0x74,
	0x77, 0x61, 0x72, 0x65, 0x2f, 0x57, 0x4d, 0x2f, 0x77, 0x6d, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x74, 0x69, 0x6c, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tiles_proto_rawDescOnce sync.Once
	file_tiles_proto_rawDescData = file_tiles_proto_rawDesc
)

func file_tiles_proto_rawDescGZIP() []byte {
	file_tiles_proto_rawDescOnce.Do(func() {
		file_tiles_proto_rawDescData = protoimpl.X.CompressGZIP(file_tiles_proto_rawDescData)
	})
	return file_tiles_proto_rawDescData
}

var file_tiles_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_tiles_proto_goTypes = []interface{}{
	(*TileStats)(nil), // 0: tiles.TileStats
	(*TileBins)(nil),  // 1: tiles.TileBins
	(*TileCoord)(nil), // 2: tiles.TileCoord
	(*Tile)(nil),      // 3: tiles.Tile
	nil,               // 4: tiles.TileBins.StatsEntry
}
var file_tiles_proto_depIdxs = []int32{
	4, // 0: tiles.TileBins.stats:type_name -> tiles.TileBins.StatsEntry
	2, // 1: tiles.Tile.coord:type_name -> tiles.TileCoord
	1, // 2: tiles.Tile.bins:type_name -> tiles.TileBins
	0, // 3: tiles.TileBins.StatsEntry.value:type_name -> tiles.TileStats
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_tiles_proto_init() }
func file_tiles_proto_init() {
	if File_tiles_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tiles_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TileStats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tiles_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TileBins); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tiles_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TileCoord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tiles_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tiles_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tiles_proto_goTypes,
		DependencyIndexes: file_tiles_proto_depIdxs,
		MessageInfos:      file_tiles_proto_msgTypes,
	}.Build()
	File_tiles_proto = out.File
	file_tiles_proto_rawDesc = nil
	file_tiles_proto_goTypes = nil
	file_tiles_proto_depIdxs = nil
}
